import Config

# Configure your database
config :band_api, BandApi.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "band_api_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :band_api, BandApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Geq2KezYDOgVlZiUy5XMQUW60MxfagBavWoUfW69A29Se9SRzGTM7WgHgT36MiMy",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :band_api, dev_routes: true

# 개발 환경에서 예쁜 로그 포맷 (시간, 레벨, 메시지, 컬러)
config :logger, :console, 
  format: "\n$time $metadata[$level] $message\n",
  level: :debug,
  metadata: [:request_id],
  colors: [enabled: true]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Band Core는 이제 라이브러리로만 동작 (웹 서버 없음)

# Band API 개발용 설정 - 환경변수에서 읽어옴
config :band_api,
  band_app_client_id: System.get_env("BAND_CLIENT_ID"),
  band_app_client_secret: System.get_env("BAND_CLIENT_SECRET")
